<?php
echo '<!DOCTYPE HTML>';
echo '<!--';
echo 'Stellar by HTML5 UP';
echo 'html5up.net | @ajlkn';
echo 'Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)';
echo '-->';
echo '<html>';
echo '<head>';
echo '<title>Elements - Stellar by HTML5 UP</title>';
echo '<meta charset="utf-8" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />';
echo '<link rel="stylesheet" href="assets/css/main.css" />';
echo '<noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>';
echo '</head>';
echo '<body class="is-preload">';
echo '';
echo '<!-- Wrapper -->';
echo '<div id="wrapper">';
echo '';
echo '<!-- Header -->';
echo '<header id="header">';
echo '<h1>Elements</h1>';
echo '<p>Ipsum dolor sit amet nullam</p>';
echo '</header>';
echo '';
echo '<!-- Main -->';
echo '<div id="main">';
echo '';
echo '<!-- Content -->';
echo '<section id="content" class="main">';
echo '';
echo '<!-- Text -->';
echo '<section>';
echo '<h2>Text</h2>';
echo '<p>This is <b>bold</b> and this is <strong>strong</strong>. This is <i>italic</i> and this is <em>emphasized</em>.';
echo 'This is <sup>superscript</sup> text and this is <sub>subscript</sub> text.';
echo 'This is <u>underlined</u> and this is code: <code>for (;;) { ... }</code>. Finally, <a href="#">this is a link</a>.</p>';
echo '<hr />';
echo '<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.</p>';
echo '<hr />';
echo '<h2>Heading Level 2</h2>';
echo '<h3>Heading Level 3</h3>';
echo '<h4>Heading Level 4</h4>';
echo '<hr />';
echo '<h3>Blockquote</h3>';
echo '<blockquote>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan faucibus. Vestibulum ante ipsum primis in faucibus lorem ipsum dolor sit amet nullam adipiscing eu felis.</blockquote>';
echo '<h3>Preformatted</h3>';
echo '<pre><code>i = 0;';
echo '';
echo 'while (!deck.isInOrder()) {';
echo 'print 'Iteration ' + i;';
echo 'deck.shuffle();';
echo 'i++;';
echo '}';
echo '';
echo 'print 'It took ' + i + ' iterations to sort the deck.';</code></pre>';
echo '</section>';
echo '';
echo '<!-- Lists -->';
echo '<section>';
echo '<h2>Lists</h2>';
echo '<div class="row">';
echo '<div class="col-6 col-12-medium">';
echo '<h3>Unordered</h3>';
echo '<ul>';
echo '<li>Dolor pulvinar magna etiam.</li>';
echo '<li>Sagittis sed lorem adipiscing.</li>';
echo '<li>Felis enim etiam feugiat.</li>';
echo '<li>Ipsum lorem nullam consequat.</li>';
echo '</ul>';
echo '<h3>Alternate</h3>';
echo '<ul class="alt">';
echo '<li>Dolor pulvinar magna etiam.</li>';
echo '<li>Sagittis sed lorem adipiscing.</li>';
echo '<li>Felis enim etiam feugiat.</li>';
echo '<li>Ipsum lorem nullam consequat.</li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-6 col-12-medium">';
echo '<h3>Ordered</h3>';
echo '<ol>';
echo '<li>Dolor pulvinar etiam.</li>';
echo '<li>Etiam vel felis viverra.</li>';
echo '<li>Felis enim feugiat.</li>';
echo '<li>Dolor pulvinar etiam.</li>';
echo '<li>Etiam vel felis lorem.</li>';
echo '<li>Felis enim et feugiat.</li>';
echo '</ol>';
echo '<h3>Icons</h3>';
echo '<ul class="icons">';
echo '<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>';
echo '<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>';
echo '<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>';
echo '<li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>';
echo '<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>';
echo '</ul>';
echo '<ul class="icons">';
echo '<li><a href="#" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>';
echo '<li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>';
echo '<li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>';
echo '<li><a href="#" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>';
echo '<li><a href="#" class="icon brands alt fa-dribbble"><span class="label">Dribbble</span></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<h2>Actions</h2>';
echo '<div class="row">';
echo '<div class="col-6 col-12-medium">';
echo '<ul class="actions">';
echo '<li><a href="#" class="button primary">Default</a></li>';
echo '<li><a href="#" class="button">Default</a></li>';
echo '</ul>';
echo '<ul class="actions small">';
echo '<li><a href="#" class="button primary small">Small</a></li>';
echo '<li><a href="#" class="button small">Small</a></li>';
echo '</ul>';
echo '<ul class="actions stacked">';
echo '<li><a href="#" class="button primary">Default</a></li>';
echo '<li><a href="#" class="button">Default</a></li>';
echo '</ul>';
echo '<ul class="actions stacked">';
echo '<li><a href="#" class="button primary small">Small</a></li>';
echo '<li><a href="#" class="button small">Small</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-6 col-12-medium">';
echo '<ul class="actions stacked">';
echo '<li><a href="#" class="button primary fit">Default</a></li>';
echo '<li><a href="#" class="button fit">Default</a></li>';
echo '</ul>';
echo '<ul class="actions stacked">';
echo '<li><a href="#" class="button primary small fit">Small</a></li>';
echo '<li><a href="#" class="button small fit">Small</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Table -->';
echo '<section>';
echo '<h2>Table</h2>';
echo '<h3>Default</h3>';
echo '<div class="table-wrapper">';
echo '<table>';
echo '<thead>';
echo '<tr>';
echo '<th>Name</th>';
echo '<th>Description</th>';
echo '<th>Price</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
echo '<tr>';
echo '<td>Item One</td>';
echo '<td>Ante turpis integer aliquet porttitor.</td>';
echo '<td>29.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Two</td>';
echo '<td>Vis ac commodo adipiscing arcu aliquet.</td>';
echo '<td>19.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Three</td>';
echo '<td> Morbi faucibus arcu accumsan lorem.</td>';
echo '<td>29.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Four</td>';
echo '<td>Vitae integer tempus condimentum.</td>';
echo '<td>19.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Five</td>';
echo '<td>Ante turpis integer aliquet porttitor.</td>';
echo '<td>29.99</td>';
echo '</tr>';
echo '</tbody>';
echo '<tfoot>';
echo '<tr>';
echo '<td colspan="2"></td>';
echo '<td>100.00</td>';
echo '</tr>';
echo '</tfoot>';
echo '</table>';
echo '</div>';
echo '';
echo '<h3>Alternate</h3>';
echo '<div class="table-wrapper">';
echo '<table class="alt">';
echo '<thead>';
echo '<tr>';
echo '<th>Name</th>';
echo '<th>Description</th>';
echo '<th>Price</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
echo '<tr>';
echo '<td>Item One</td>';
echo '<td>Ante turpis integer aliquet porttitor.</td>';
echo '<td>29.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Two</td>';
echo '<td>Vis ac commodo adipiscing arcu aliquet.</td>';
echo '<td>19.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Three</td>';
echo '<td> Morbi faucibus arcu accumsan lorem.</td>';
echo '<td>29.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Four</td>';
echo '<td>Vitae integer tempus condimentum.</td>';
echo '<td>19.99</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Item Five</td>';
echo '<td>Ante turpis integer aliquet porttitor.</td>';
echo '<td>29.99</td>';
echo '</tr>';
echo '</tbody>';
echo '<tfoot>';
echo '<tr>';
echo '<td colspan="2"></td>';
echo '<td>100.00</td>';
echo '</tr>';
echo '</tfoot>';
echo '</table>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Buttons -->';
echo '<section>';
echo '<h3>Buttons</h3>';
echo '<ul class="actions">';
echo '<li><a href="#" class="button primary">Primary</a></li>';
echo '<li><a href="#" class="button">Default</a></li>';
echo '</ul>';
echo '<ul class="actions">';
echo '<li><a href="#" class="button large">Large</a></li>';
echo '<li><a href="#" class="button">Default</a></li>';
echo '<li><a href="#" class="button small">Small</a></li>';
echo '</ul>';
echo '<ul class="actions fit">';
echo '<li><a href="#" class="button primary fit">Fit</a></li>';
echo '<li><a href="#" class="button fit">Fit</a></li>';
echo '<li><a href="#" class="button fit">Fit</a></li>';
echo '</ul>';
echo '<ul class="actions fit small">';
echo '<li><a href="#" class="button primary fit small">Fit + Small</a></li>';
echo '<li><a href="#" class="button fit small">Fit + Small</a></li>';
echo '<li><a href="#" class="button fit small">Fit + Small</a></li>';
echo '</ul>';
echo '<ul class="actions">';
echo '<li><a href="#" class="button primary icon solidfa-download">Icon</a></li>';
echo '<li><a href="#" class="button icon solid fa-upload">Icon</a></li>';
echo '<li><a href="#" class="button icon solid fa-save">Icon</a></li>';
echo '</ul>';
echo '<ul class="actions">';
echo '<li><span class="button primary disabled">Disabled</span></li>';
echo '<li><span class="button disabled">Disabled</span></li>';
echo '</ul>';
echo '</section>';
echo '';
echo '<!-- Form -->';
echo '<section>';
echo '<h2>Form</h2>';
echo '<form method="post" action="#">';
echo '<div class="row gtr-uniform">';
echo '<div class="col-6 col-12-xsmall">';
echo '<input type="text" name="demo-name" id="demo-name" value="" placeholder="Name" />';
echo '</div>';
echo '<div class="col-6 col-12-xsmall">';
echo '<input type="email" name="demo-email" id="demo-email" value="" placeholder="Email" />';
echo '</div>';
echo '<div class="col-12">';
echo '<select name="demo-category" id="demo-category">';
echo '<option value="">- Category -</option>';
echo '<option value="1">Manufacturing</option>';
echo '<option value="1">Shipping</option>';
echo '<option value="1">Administration</option>';
echo '<option value="1">Human Resources</option>';
echo '</select>';
echo '</div>';
echo '<div class="col-4 col-12-small">';
echo '<input type="radio" id="demo-priority-low" name="demo-priority" checked>';
echo '<label for="demo-priority-low">Low</label>';
echo '</div>';
echo '<div class="col-4 col-12-small">';
echo '<input type="radio" id="demo-priority-normal" name="demo-priority">';
echo '<label for="demo-priority-normal">Normal</label>';
echo '</div>';
echo '<div class="col-4 col-12-small">';
echo '<input type="radio" id="demo-priority-high" name="demo-priority">';
echo '<label for="demo-priority-high">High</label>';
echo '</div>';
echo '<div class="col-6 col-12-small">';
echo '<input type="checkbox" id="demo-copy" name="demo-copy">';
echo '<label for="demo-copy">Email me a copy</label>';
echo '</div>';
echo '<div class="col-6 col-12-small">';
echo '<input type="checkbox" id="demo-human" name="demo-human" checked>';
echo '<label for="demo-human">Not a robot</label>';
echo '</div>';
echo '<div class="col-12">';
echo '<textarea name="demo-message" id="demo-message" placeholder="Enter your message" rows="6"></textarea>';
echo '</div>';
echo '<div class="col-12">';
echo '<ul class="actions">';
echo '<li><input type="submit" value="Send Message" class="primary" /></li>';
echo '<li><input type="reset" value="Reset" /></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</section>';
echo '';
echo '<!-- Image -->';
echo '<section>';
echo '<h2>Image</h2>';
echo '<h3>Fit</h3>';
echo '<div class="box alt">';
echo '<div class="row gtr-uniform">';
echo '<div class="col-12"><span class="image fit"><img src="images/pic04.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic01.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic02.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic03.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic03.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic01.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic02.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic02.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic03.jpg" alt="" /></span></div>';
echo '<div class="col-4"><span class="image fit"><img src="images/pic01.jpg" alt="" /></span></div>';
echo '</div>';
echo '</div>';
echo '<h3>Left &amp; Right</h3>';
echo '<p><span class="image left"><img src="images/pic05.jpg" alt="" /></span>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent lorem ipsum dolor sit amet veroeros consequat. Etiam tempus lorem ipsum.</p>';
echo '<p><span class="image right"><img src="images/pic06.jpg" alt="" /></span>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus..</p>';
echo '</section>';
echo '';
echo '</section>';
echo '';
echo '</div>';
echo '';
echo '<!-- Footer -->';
echo '<footer id="footer">';
echo '<section>';
echo '<h2>Aliquam sed mauris</h2>';
echo '<p>Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio.</p>';
echo '<ul class="actions">';
echo '<li><a href="#" class="button">Learn More</a></li>';
echo '</ul>';
echo '</section>';
echo '<section>';
echo '<h2>Etiam feugiat</h2>';
echo '<dl class="alt">';
echo '<dt>Address</dt>';
echo '<dd>1234 Somewhere Road &bull; Nashville, TN 00000 &bull; USA</dd>';
echo '<dt>Phone</dt>';
echo '<dd>(000) 000-0000 x 0000</dd>';
echo '<dt>Email</dt>';
echo '<dd><a href="#">information@untitled.tld</a></dd>';
echo '</dl>';
echo '<ul class="icons">';
echo '<li><a href="#" class="icon brands fa-twitter alt"><span class="label">Twitter</span></a></li>';
echo '<li><a href="#" class="icon brands fa-facebook-f alt"><span class="label">Facebook</span></a></li>';
echo '<li><a href="#" class="icon brands fa-instagram alt"><span class="label">Instagram</span></a></li>';
echo '<li><a href="#" class="icon brands fa-github alt"><span class="label">GitHub</span></a></li>';
echo '<li><a href="#" class="icon brands fa-dribbble alt"><span class="label">Dribbble</span></a></li>';
echo '</ul>';
echo '</section>';
echo '<p class="copyright">&copy; Untitled. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>';
echo '</footer>';
echo '';
echo '</div>';
echo '';
echo '<!-- Scripts -->';
echo '<script src="assets/js/jquery.min.js"></script>';
echo '<script src="assets/js/jquery.scrollex.min.js"></script>';
echo '<script src="assets/js/jquery.scrolly.min.js"></script>';
echo '<script src="assets/js/browser.min.js"></script>';
echo '<script src="assets/js/breakpoints.min.js"></script>';
echo '<script src="assets/js/util.js"></script>';
echo '<script src="assets/js/main.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>