<?php
echo '<!DOCTYPE HTML>';
echo '<html>';
echo '<head><meta charset="utf-8">';
echo '<title>الکتروموتیو</title>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />';
echo '<link href="assets/css/main.css" rel="stylesheet" /><noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>';
echo '</head>';
echo '<body class="is-preload"><!-- Wrapper -->';
echo '<div id="wrapper"><!-- Header -->';
echo '<header class="alt" id="header"><!--	<span class="logo"><img src="images/Logo.JPG" alt="" /></span>-->';
echo '<h1>الکتروموتیو</h1>';
echo '';
echo '<p>. . . این سامانه در حال بروزرسانی است. لطفا شکیبا باشید</p>';
echo '';
echo '<p style="margin-bottom:0.1cm;">طراحی شده توسط</p>';
echo '<a href="https://www.linkedin.com/in/danial-firouzimagham/">دانـیـال </a>&nbsp;&nbsp;<a href="https://www.linkedin.com/in/paminai/">پویــا </a>';
echo '';
echo '<p></p>';
echo '</header>';
echo '<!-- Nav -->';
echo '';
echo '<nav id="nav">';
echo '<div style="background:#eee;border:1px solid #ccc;padding:5px 10px;"><span style="font-family:comic sans ms,cursive;">هوشمند سازی صنعت برق</span></div>';
echo '</nav>';
echo '<!-- Main -->';
echo '';
echo '<div id="main"><!-- Introduction -->';
echo '<section class="main" id="intro">';
echo '<div class="spotlight">';
echo '<div class="content">';
echo '<header class="major">';
echo '<h2 style="text-align: right;">معرفی سامانه الکتــروموتـیـــو</h2>';
echo '</header>';
echo '';
echo '<p dir="rtl" style="text-align: justify;">الکترومـوتـیـو یک سامانه هوشمند پایش نیروگاه های برق است که با طراحی یک دیوایس الکترونیکی مجهز به اینترنت اشیا و همچنین&nbsp;به کمک الگوریتم های هوش مصنوعی باعث بهینه سازی مصرف انرژی های تجدیدپذیر در کشور خواهد شد.&nbsp;سامانه در حال حاضر در دست توسعه و بروزرسانی است از شکیبایی شما سپاس گزاریم.</p>';
echo '';
echo '<p dir="rtl" style="text-align: justify;"></p>';
echo '</div>';
echo '<span class="image"><img alt="" src="images/pic01.jpg" /></span></div>';
echo '</section>';
echo '</div>';
echo '';
echo '<footer id="footer">';
echo '<p class="copyright"><span style="font-size:14px;"><strong>&nbsp;2021 &copy;</strong>&nbsp;&nbsp;<strong>تمام حقوق این سایت محفوظ است.&nbsp;| طراحی شده&nbsp;توسط&nbsp; &nbsp;&nbsp;<em>الـکــتــرومـوتیـــو</em></strong></span></p>';
echo '</footer>';
echo '</div>';
echo '<!-- Scripts --><script src="assets/js/jquery.min.js"></script><script src="assets/js/jquery.scrollex.min.js"></script><script src="assets/js/jquery.scrolly.min.js"></script><script src="assets/js/browser.min.js"></script><script src="assets/js/breakpoints.min.js"></script><script src="assets/js/util.js"></script><script src="assets/js/main.js"></script></body>';
echo '</html>';
?>